baseURL = "https://www.meath.cloud"
languageCode = "en-us"
title = "Derrek"
theme = "hello-friend-ng"
[pagination]
  pagerSize = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  defaultTheme    = "dark"
  description     = "IT Manager"
  homeSubtitle    = "IT Manager"

[params.logo]
  logoText     = "~/meathcloud"
  logoHomeLink = "/"

[[params.social]]
  name = "github"
  url  = "https://github.com/ctrigga"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/derrek-meath-22864051"

  [[params.social]]
  name = "email"
  url  = "mailto:derrek@meath.cloud"

[params]
  appInsightsConnectionString = "InstrumentationKey=dbc8bbae-5369-4e1d-8df8-2f53a17e9c48;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=9ae4d96e-36f2-4918-928a-50a89d333760"

[taxonomies]
  tag      = "tags"
  category = "blog"
  series   = "series"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 10
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
    weight     = 20
  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "/resume/"
    weight     = 30
  [[menu.main]]
    identifier = "f1"
    name = "F1"
    url = "/f1/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true